[workspace]
resolver = "2"
members = [
    "core",
    "cli"
]
default-members = ["cli"]

[workspace.dependencies]
anyhow = "1.0"
thiserror = "2.0"
chumsky = "0.9"
cranelift = "0.108"
cranelift-jit = "0.108"
cranelift-module = "0.108"
cranelift-native = "0.108"
cranelift-frontend = "0.108"
cranelift-codegen = "0.108"
rustyline = "14.0"
tracing = "0.1"
dirs = "5.0"
# ... and other deps shared across crates if desired
