[package]
name = "dlisp-core"
version = "0.1.0"
edition = "2024"

[dependencies]
# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Parsing
chumsky = { workspace = true }

# JIT Compiler
cranelift = { workspace = true }
cranelift-jit = { workspace = true }
cranelift-module = { workspace = true }
cranelift-native = { workspace = true }
cranelift-frontend = { workspace = true }
cranelift-codegen = { workspace = true }
cranelift-object = { workspace = true }

# REPL
rustyline = { workspace = true }

# Logging/Tracing
tracing = { workspace = true }
tracing-subscriber = "0.3"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.futures]
version = "0.3"

[dependencies.async-recursion]
version = "1"

[dev-dependencies]
dlisp_runtime = { path = "../runtime" }
