#!/usr/bin/env python3
"""Generate docs/ai/generated/symbol-index.md.

A lookup table for AI agents: map every user-visible language symbol to its
definition site so agents can jump straight to code instead of grepping.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT_DIR / "docs/ai/generated/symbol-index.md"

GENERATED_HEADER = (
    "<!-- generated by scripts/gen_symbol_index.py; do not edit -->"
)


def read_lines(path: Path) -> list[str]:
    try:
        return path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError:
        raise SystemExit(f"failed to locate {path}") from None


def rel(path: Path) -> str:
    return path.relative_to(ROOT_DIR).as_posix()


def special_forms() -> list[tuple[str, str]]:
    registry = ROOT_DIR / "core/src/forms/registry.rs"
    lines = read_lines(registry)
    entries: list[tuple[str, str]] = []
    for no, line in enumerate(lines, start=1):
        match = re.search(r'reg\.register\(\s*"([^"]+)"', line)
        if match:
            entries.append((match.group(1), f"{rel(registry)}:{no}"))

    interpreter = ROOT_DIR / "core/src/interpreter.rs"
    for no, line in enumerate(read_lines(interpreter), start=1):
        if re.search(r'\bs\s*==\s*"defmacro"', line):
            entries.append(("defmacro", f"{rel(interpreter)}:{no}"))
            break
    return entries


def compiled_builtins() -> set[str]:
    mod_rs = read_lines(ROOT_DIR / "core/src/codegen/mod.rs")
    names: set[str] = set()
    in_list = False
    for line in mod_rs:
        if "COMPILED_BUILTINS" in line:
            in_list = True
            continue
        if in_list:
            if line.strip().startswith("]"):
                break
            for name in re.findall(r'"([^"]+)"', line):
                names.add(name)
    return names


def builtins(compiled: set[str]) -> list[tuple[str, str]]:
    mod_path = ROOT_DIR / "core/src/builtins/mod.rs"
    entries: list[tuple[str, str]] = []
    for no, line in enumerate(read_lines(mod_path), start=1):
        match = re.search(r'env\.set\(\s*"([^"]+)"\.to_string\(', line)
        if match:
            name = match.group(1)
            marker = " [compiled]" if name in compiled else ""
            entries.append((f"{name}{marker}", f"{rel(mod_path)}:{no}"))
    return entries


def ffi_exports() -> list[tuple[str, str]]:
    pattern = re.compile(r'extern\s+"C"\s+fn\s+(dlisp_[a-z0-9_]+)')
    entries: list[tuple[str, str]] = []
    for path in sorted((ROOT_DIR / "runtime/src").glob("*.rs")):
        for no, line in enumerate(read_lines(path), start=1):
            for name in pattern.findall(line):
                entries.append((name, f"{rel(path)}:{no}"))
    return entries


def stdlib_surface() -> list[tuple[str, str]]:
    core_lisp = ROOT_DIR / "stdlib/src/core.lisp"
    pattern = re.compile(r"\((defun|defmacro)\s+\(?([^\s()\[\]]+)")
    entries: list[tuple[str, str]] = []
    for no, line in enumerate(read_lines(core_lisp), start=1):
        for kind, name in pattern.findall(line):
            entries.append((name, f"{rel(core_lisp)}:{no} ({kind})"))
    return entries


def render_section(title: str, intro: str, entries: list[tuple[str, str]]) -> list[str]:
    out = [f"## {title}", "", intro, ""]
    for name, where in sorted(entries, key=lambda e: e[0]):
        out.append(f"- `{name}` — {where}")
    out.append("")
    return out


def generate() -> str:
    compiled = compiled_builtins()
    lines = [
        GENERATED_HEADER,
        "",
        "# dlisp symbol index",
        "",
        "Lookup table for AI agents: jump straight to the definition instead of grepping.",
        "[compiled] means the name is in `COMPILED_BUILTINS` and lowers to runtime FFI.",
        "",
    ]
    lines += render_section(
        "Special forms",
        "Registered in the evaluator registry.",
        special_forms(),
    )
    lines += render_section(
        "Builtins",
        "Registered into the default environment.",
        builtins(compiled),
    )
    lines += render_section(
        "Runtime FFI exports",
        "`extern \"C\"` symbols linked by JIT/AOT codegen.",
        ffi_exports(),
    )
    lines += render_section(
        "Bundled stdlib",
        "Lisp-level definitions loaded by `(require \"core\")`.",
        stdlib_surface(),
    )
    return "\n".join(lines)


def main() -> int:
    output = generate()
    if len(sys.argv) > 1 and sys.argv[1] == "--write":
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_text(output, encoding="utf-8")
        print(f"wrote {rel(OUTPUT_PATH)}")
        return 0
    print(output, end="" if output.endswith("\n") else "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
