(defun main ()
  (let ((m {:a 1 :b 2})
        (m2 (hash-map :c 3 :d 4)))
    (print m)
    (print m2)
    (print (get m :a))
    (print (get m2 :c))
    (print (get m :not-found))
    (print (assoc m :a 100))
    (print (assoc m2 :e 5))
    (print (map? m))
    (print (type-of m))))
